import os
from dotenv import load_dotenv

load_dotenv()

LOCK_TIMEOUT_MINUTES = 5
JOB_INTERVAL_SECONDS = 60
REPLY_CHECK_INTERVAL_SECONDS = int(os.getenv("REPLY_CHECK_INTERVAL_SECONDS", "300"))
MAX_LEADS_PER_RUN = 50
MAX_CONCURRENT_GENERATIONS = 10
CAMPAIGN_EMAIL_RATE_LIMIT = 50
RATE_LIMIT_WINDOW_MINUTES = 60
