import os

LOCK_TIMEOUT_MINUTES = int(os.getenv("LOCK_TIMEOUT_MINUTES", "5"))
JOB_INTERVAL_SECONDS = int(os.getenv("JOB_INTERVAL_SECONDS", "60"))
REPLY_CHECK_INTERVAL_SECONDS = int(os.getenv("REPLY_CHECK_INTERVAL_SECONDS", "300"))
CAMPAIGN_CHECK_INTERVAL_SECONDS = int(os.getenv("CAMPAIGN_CHECK_INTERVAL_SECONDS", "60"))
MAX_LEADS_PER_RUN = int(os.getenv("MAX_LEADS_PER_RUN", "50"))
MAX_CONCURRENT_GENERATIONS = int(os.getenv("MAX_CONCURRENT_GENERATIONS", "10"))
CAMPAIGN_EMAIL_RATE_LIMIT = int(os.getenv("CAMPAIGN_EMAIL_RATE_LIMIT", "50"))
RATE_LIMIT_WINDOW_MINUTES = int(os.getenv("RATE_LIMIT_WINDOW_MINUTES", "60"))